In [1]:
#Import the neccessary Libraries
%matplotlib inline 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
from sklearn import model_selection
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics

In [2]:
!pwd

/Users/hariprasadshanmugavelu

In [3]:
!cd Downloads

In [4]:
!pwd

/Users/hariprasadshanmugavelu

In [5]:
import sys

# Add the directory to the system path
sys.path.append('/Users/hariprasadshanmugavelu/Downloads')

In [6]:
!pwd

/Users/hariprasadshanmugavelu

In [7]:
import os

# Check current working directory
print("Current:", os.getcwd())

Current: /Users/hariprasadshanmugavelu

In [8]:
os.chdir('/Users/hariprasadshanmugavelu/Downloads')

In [9]:
!pwd

/Users/hariprasadshanmugavelu/Downloads

In [52]:
#Read the data as a dataframe
capstone = pd.read_csv('RealEstate_Dubai.csv')

In [11]:
capstone.shape

(872031, 47)

In [12]:
capstone.head(5)

,actual_worth,area_id,area_name_ar,area_name_en,building_name_ar,building_name_en,has_parking,instance_date,master_project_ar,master_project_en,...,reg_type_en,reg_type_id,rent_value,rooms_ar,rooms_en,transaction_id,trans_group_ar,trans_group_en,trans_group_id,load_timestamp
0,1600000.0,441,البرشاء جنوب الرابعة,Al Barsha South Fourth,NaN,NaN,0,2018-04-11,قرية جميرا الدائرية,Jumeirah Village Circle,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,1-11-2018-3852,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
1,460000.0,465,وادي الصفا 3,Wadi Al Safa 3,سمايا,SAMAYA,1,2024-08-08,ماجان,Majan,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2024-29367,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
2,960000.0,526,الخليج التجارى,Business Bay,واترز ايدج,WATER'S EDGE,1,2024-06-04,الخليج التجاري,Business Bay,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2024-20211,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
3,317000.0,343,ورسان الاولى,Al Warsan First,واي - 20,Y-20,0,2013-08-12,المدينة العالمية - المرحلة الاولى,International City Phase 1,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2013-24109,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
4,1750000.0,330,مرسى دبي,Marsa Dubai,فيدا ريزيدنسز دبي مارينا,VIDA Residences Dubai Marina,1,2022-11-22,دبي مارينا,Dubai Marina,...,Off-Plan Properties,0,NaN,غرفة,1 B/R,1-102-2022-38762,مبايعات,Sales,1,2026-07-08T18:22:29.000Z

In [13]:
#Data Type of each attribute
capstone.dtypes

actual_worth            float64
area_id                   int64
area_name_ar                str
area_name_en                str
building_name_ar            str
building_name_en            str
has_parking               int64
instance_date               str
master_project_ar           str
master_project_en           str
meter_rent_price        float64
meter_sale_price        float64
nearest_landmark_ar         str
nearest_landmark_en         str
nearest_mall_ar             str
nearest_mall_en             str
nearest_metro_ar            str
nearest_metro_en            str
no_of_parties_role_1    float64
no_of_parties_role_2    float64
no_of_parties_role_3    float64
procedure_area          float64
procedure_id              int64
procedure_name_ar           str
procedure_name_en           str
project_name_ar             str
project_name_en             str
project_number          float64
property_sub_type_ar        str
property_sub_type_en        str
property_sub_type_id    float64
property_type_ar            str
property_type_en            str
property_type_id          int64
property_usage_ar           str
property_usage_en           str
reg_type_ar                 str
reg_type_en                 str
reg_type_id               int64
rent_value              float64
rooms_ar                    str
rooms_en                    str
transaction_id              str
trans_group_ar              str
trans_group_en              str
trans_group_id            int64
load_timestamp              str
dtype: object

In [14]:
#Exploratory Data Analysis
capstone.describe().T

,count,mean,std,min,25%,50%,75%,max
actual_worth,872031.0,3.830475e+06,5.609464e+07,1.00,750000.00,1359888.00,2521860.00,1.378694e+10
area_id,872031.0,4.182577e+02,6.742697e+01,229.00,350.00,441.00,465.00,5.310000e+02
has_parking,872031.0,6.696081e-01,4.703545e-01,0.00,0.00,1.00,1.00,1.000000e+00
meter_rent_price,18425.0,1.949574e+04,2.801725e+05,0.01,5146.35,7263.00,10387.24,1.085667e+07
meter_sale_price,872031.0,1.539945e+04,1.022200e+05,0.00,7521.59,11873.15,17979.28,3.499578e+07
no_of_parties_role_1,871540.0,1.239758e+00,2.993708e+00,0.00,1.00,1.00,1.00,5.450000e+02
no_of_parties_role_2,871540.0,1.181503e+00,5.043218e-01,0.00,1.00,1.00,1.00,7.800000e+01
no_of_parties_role_3,871540.0,1.014434e-01,5.048556e-01,0.00,0.00,0.00,0.00,1.700000e+01
procedure_area,872031.0,1.310470e+03,3.769364e+05,0.02,69.00,110.28,210.00,3.421034e+08
procedure_id,872031.0,6.192120e+01,8.684982e+01,4.00,11.00,41.00,102.00,8.610000e+02
project_number,639467.0,1.925317e+03,1.044786e+03,2.00,1277.00,1852.00,2644.00,4.498000e+03
property_sub_type_id,700066.0,5.391991e+01,1.999005e+01,2.00,60.00,60.00,60.00,1.120000e+02
property_type_id,872031.0,2.975859e+00,7.416920e-01,1.00,3.00,3.00,3.00,4.000000e+00
reg_type_id,872031.0,6.387101e-01,4.803746e-01,0.00,0.00,1.00,1.00,1.000000e+00
rent_value,18425.0,1.487944e+06,2.923148e+06,2.00,600000.00,1020000.00,1810000.00,2.620800e+08
trans_group_id,872031.0,1.270729e+00,5.212977e-01,1.00,1.00,1.00,1.00,3.000000e+00

In [15]:
capstone["actual_worth"].mean()

np.float64(3830474.639370619)

In [16]:
round(capstone["actual_worth"].mean(), 2)

np.float64(3830474.64)

In [17]:
capstone["actual_worth"].median()

np.float64(1359888.0)

In [18]:
capstone["instance_date"].value_counts(ascending=True)

instance_date
1997-08-21       1
1996-06-25       1
1993-07-13       1
2000-09-20       1
1993-12-28       1
              ...
2025-07-21     964
2009-10-26    1036
2025-12-29    1080
2010-03-03    1172
2023-09-11    1460
Name: count, Length: 6358, dtype: int64

In [19]:
capstone['instance_date'] = pd.to_datetime(capstone['instance_date'], errors='coerce')

In [20]:
capstone["trans_group_en"]

0         Sales
1         Sales
2         Sales
3         Sales
4         Sales
          ...
872026    Sales
872027    Sales
872028    Sales
872029    Sales
872030    Sales
Name: trans_group_en, Length: 872031, dtype: str

In [21]:
capstone["trans_group_en"].unique()

<StringArray>
['Sales', 'Mortgages', 'Gifts']
Length: 3, dtype: str

In [22]:
capstone["procedure_name_en"].unique()

<StringArray>
[                                            'Sell',
                          'Sell - Pre registration',
                        'Lease to Own Registration',
                            'Mortgage Registration',
                                 'Sell Development',
                                     'Delayed Sell',
                                  'Modify Mortgage',
                         'Development Registration',
                              'Delayed Development',
                            'Grant on Delayed Sell',
        'Development Registration Pre-Registration',
                       'Lease Finance Modification',
                                 'Delayed Mortgage',
                                            'Grant',
                       'Lease Finance Registration',
         'Lease to Own on Development Registration',
                             'Development Mortgage',
       'Lease to Own Registration Pre-Registration',
                   'Lease Development Registration',
                             'Sale On Payment Plan',
                                'Mortgage Transfer',
                      'Modify Development Mortgage',
                           'Grant Pre-Registration',
                  'Portfolio Mortgage Modification',
                        'Mortgage Pre-Registration',
                            'Lease to Own Transfer',
           'Delayed Sell Lease to Own Registration',
                  'Portfolio Mortgage Registration',
                'Delayed Lease to Own Registration',
                                'Grant Development',
                              'Adding Land By Sell',
                              'Lease to Own Modify',
                          'Modify Delayed Mortgage',
                 'Modify Mortgage Pre-Registration',
                         'Delayed Sell Development',
              'Sell Development - Pre Registration',
                       'Delayed Portfolio Mortgage',
      'Portfolio Mortgage Development Registration',
 'Portfolio Mortgage Modification Pre-Registration',
      'Portfolio Mortgage Development Modification',
               'Portfolio Development Registration',
 'Portfolio Mortgage Registration Pre-Registration',
         'Lease to Own on Development Modification',
               'Mortgage Transfer Pre-Registration',
                         'Lease Development Modify',
                      'Delayed Lease to Own Modify',
                    'Transfer Development Mortgage',
            'Development Mortgage Pre-Registration',
           'Delayed Sell Lease To Own Modification',
                      'Portfolio Mortgage Transfer',
           'Lease to Own Transfer Pre-Registration']
Length: 51, dtype: str

In [23]:
capstone["rooms_en"].unique()

<StringArray>
[      '3 B/R',      'Studio',       '1 B/R',       '2 B/R',           nan,
      'Office', 'Single Room',       '4 B/R',       '5 B/R',        'Shop',
   'PENTHOUSE',       'Store',       '6 B/R',       '7 B/R',       '8 B/R',
         'GYM',       '9 B/R',      '10 B/R']
Length: 18, dtype: str

In [24]:
capstone["property_type_en"].unique()

<StringArray>
['Villa', 'Unit', 'Land', 'Building']
Length: 4, dtype: str

In [25]:
capstone["master_project_en"].unique()

<StringArray>
[            'Jumeirah Village Circle',                               'Majan',
                        'Business Bay',          'International City Phase 1',
                        'Dubai Marina',               'DMCC Master Community',
                      'Barsha Heights',                         'TOWN SQUARE',
 'International Media Production Zone',                  'Dubai Science Park',
 ...
                        'Burj Khalifa',                     'Al Khail Towers',
                'Dubai Outsource City',                         'The Gardens',
                      'Emirates Hills',                        'TECOM Site B',
                        'TECOM Site A',                        'TECOM Site C',
            'DUBAI HILLS - PALM HILLS',                           'Meadows 5']
Length: 160, dtype: str

In [26]:
capstone["reg_type_en"].unique()

<StringArray>
['Existing Properties', 'Off-Plan Properties']
Length: 2, dtype: str

In [27]:
capstone["instance_date"]

0        2018-04-11
1        2024-08-08
2        2024-06-04
3        2013-08-12
4        2022-11-22
            ...
872026   2024-11-12
872027   2025-10-07
872028   2023-08-21
872029   2013-04-23
872030   2016-07-21
Name: instance_date, Length: 872031, dtype: datetime64[us]

In [28]:
capstone["instance_date"].value_counts(ascending=True)

instance_date
1997-08-21       1
1996-06-25       1
1993-07-13       1
2000-09-20       1
1993-12-28       1
              ...
2025-07-21     964
2009-10-26    1036
2025-12-29    1080
2010-03-03    1172
2023-09-11    1460
Name: count, Length: 6358, dtype: int64

In [29]:
capstone.dtypes

actual_worth                   float64
area_id                          int64
area_name_ar                       str
area_name_en                       str
building_name_ar                   str
building_name_en                   str
has_parking                      int64
instance_date           datetime64[us]
master_project_ar                  str
master_project_en                  str
meter_rent_price               float64
meter_sale_price               float64
nearest_landmark_ar                str
nearest_landmark_en                str
nearest_mall_ar                    str
nearest_mall_en                    str
nearest_metro_ar                   str
nearest_metro_en                   str
no_of_parties_role_1           float64
no_of_parties_role_2           float64
no_of_parties_role_3           float64
procedure_area                 float64
procedure_id                     int64
procedure_name_ar                  str
procedure_name_en                  str
project_name_ar                    str
project_name_en                    str
project_number                 float64
property_sub_type_ar               str
property_sub_type_en               str
property_sub_type_id           float64
property_type_ar                   str
property_type_en                   str
property_type_id                 int64
property_usage_ar                  str
property_usage_en                  str
reg_type_ar                        str
reg_type_en                        str
reg_type_id                      int64
rent_value                     float64
rooms_ar                           str
rooms_en                           str
transaction_id                     str
trans_group_ar                     str
trans_group_en                     str
trans_group_id                   int64
load_timestamp                     str
dtype: object

In [30]:
capstone["instance_date"]

0        2018-04-11
1        2024-08-08
2        2024-06-04
3        2013-08-12
4        2022-11-22
            ...
872026   2024-11-12
872027   2025-10-07
872028   2023-08-21
872029   2013-04-23
872030   2016-07-21
Name: instance_date, Length: 872031, dtype: datetime64[us]

In [31]:
capstone["rent_value"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
872026   NaN
872027   NaN
872028   NaN
872029   NaN
872030   NaN
Name: rent_value, Length: 872031, dtype: float64

In [32]:
capstone["rent_value"].head(100)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: rent_value, Length: 100, dtype: float64

In [34]:
#Read the data as a dataframe
capstone_ejari = pd.read_csv('rent_contracts_2026-07-08_18-34-43_0001.csv')

In [35]:
capstone_ejari.shape

(1024931, 41)

In [36]:
capstone_ejari.head()

,actual_area,annual_amount,area_id,area_name_ar,area_name_en,contract_amount,contract_end_date,contract_id,contract_reg_type_ar,contract_reg_type_en,...,no_of_prop,project_name_ar,project_name_en,project_number,property_usage_ar,property_usage_en,tenant_type_ar,tenant_type_en,tenant_type_id,load_timestamp
0,5431.0,86625.0,232.0,مردف,Mirdif,86625.0,2025-01-04,CNT2114475016,جديد,New,...,1,NaN,NaN,NaN,سكني,Residential,شخص,Person,0.0,2026-07-08T18:25:35.000Z
1,55.0,32500.0,339.0,المرر,Al Mararr,32500.0,2022-12-31,CNT1823006931,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
2,1.0,180000.0,359.0,الطوار الثالثه,Al Twar Third,180000.0,2022-01-31,CRT1480009276,تجديد,Renew,...,1,NaN,NaN,NaN,سكني,Residential,شخص,Person,0.0,2026-07-08T18:25:35.000Z
3,106.1,180000.0,526.0,الخليج التجارى,Business Bay,60000.0,2025-03-21,CNT2125814966,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
4,96.0,57000.0,267.0,الرفاعه,Al Raffa,57000.0,2022-02-28,CNT1377977270,تجديد,Renew,...,1,NaN,NaN,NaN,سكني,Residential,جهة,Authority,1.0,2026-07-08T18:25:35.000Z

In [37]:
capstone_ejari.dtypes

actual_area                   float64
annual_amount                 float64
area_id                       float64
area_name_ar                      str
area_name_en                      str
contract_amount               float64
contract_end_date                 str
contract_id                       str
contract_reg_type_ar              str
contract_reg_type_en              str
contract_reg_type_id            int64
contract_start_date               str
ejari_bus_property_type_ar        str
ejari_bus_property_type_en        str
ejari_bus_property_type_id    float64
ejari_property_sub_type_ar        str
ejari_property_sub_type_en        str
ejari_property_sub_type_id    float64
ejari_property_type_ar            str
ejari_property_type_en            str
ejari_property_type_id        float64
is_free_hold                  float64
line_number                     int64
master_project_ar                 str
master_project_en                 str
nearest_landmark_ar               str
nearest_landmark_en               str
nearest_mall_ar                   str
nearest_mall_en                   str
nearest_metro_ar                  str
nearest_metro_en                  str
no_of_prop                      int64
project_name_ar                   str
project_name_en                   str
project_number                float64
property_usage_ar                 str
property_usage_en                 str
tenant_type_ar                    str
tenant_type_en                    str
tenant_type_id                float64
load_timestamp                    str
dtype: object

In [38]:
#Read the data as a dataframe
capstone_ejari_2 = pd.read_csv('rent_contracts_2026-07-08_18-34-43_0002.csv')

In [39]:
capstone_ejari_2.shape

(1024931, 41)

In [40]:
capstone_ejari_2.head()

,actual_area,annual_amount,area_id,area_name_ar,area_name_en,contract_amount,contract_end_date,contract_id,contract_reg_type_ar,contract_reg_type_en,...,no_of_prop,project_name_ar,project_name_en,project_number,property_usage_ar,property_usage_en,tenant_type_ar,tenant_type_en,tenant_type_id,load_timestamp
0,79.99,138000.0,465,وادي الصفا 3,Wadi Al Safa 3,138000.0,2019-08-19,CNT848254060,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
1,NaN,66667.0,319,راس الخور الصناعيه الثانيه,Ras Al Khor Industrial Second,66667.0,2023-11-24,CNT2052130227,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
2,65.70,80000.0,334,الجداف,Al Jadaf,80000.0,2026-04-09,CRT2130401186,جديد,New,...,1,D1,D1,623.0,سكني,Residential,شخص,Person,0.0,2026-07-08T18:25:35.000Z
3,55.72,39000.0,372,القوز الصناعيه الثانيه,Al Goze Industrial Second,39000.0,2025-07-21,CNT2117553166,تجديد,Renew,...,1,NaN,NaN,NaN,سكني,Residential,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
4,673.00,724400.0,463,وادي الصفا 7,Wadi Al Safa 7,724400.0,2019-01-31,CNT743999615,جديد,New,...,1,المدينة المستدامة,THE SUSTAINABLE CITY,1390.0,منشأه صحيه,Health Facility,جهة,Authority,1.0,2026-07-08T18:25:35.000Z

In [41]:
capstone_ejari_2.dtypes

actual_area                   float64
annual_amount                 float64
area_id                         int64
area_name_ar                      str
area_name_en                      str
contract_amount               float64
contract_end_date                 str
contract_id                       str
contract_reg_type_ar              str
contract_reg_type_en              str
contract_reg_type_id            int64
contract_start_date               str
ejari_bus_property_type_ar        str
ejari_bus_property_type_en        str
ejari_bus_property_type_id    float64
ejari_property_sub_type_ar        str
ejari_property_sub_type_en        str
ejari_property_sub_type_id    float64
ejari_property_type_ar            str
ejari_property_type_en            str
ejari_property_type_id        float64
is_free_hold                  float64
line_number                     int64
master_project_ar                 str
master_project_en                 str
nearest_landmark_ar               str
nearest_landmark_en               str
nearest_mall_ar                   str
nearest_mall_en                   str
nearest_metro_ar                  str
nearest_metro_en                  str
no_of_prop                      int64
project_name_ar                   str
project_name_en                   str
project_number                float64
property_usage_ar                 str
property_usage_en                 str
tenant_type_ar                    str
tenant_type_en                    str
tenant_type_id                float64
load_timestamp                    str
dtype: object

In [42]:
capstone_ejari_2["project_name_en"]

0                           NaN
1                           NaN
2                            D1
3                           NaN
4          THE SUSTAINABLE CITY
                   ...
1024926                NILOOFAR
1024927                     NaN
1024928                     NaN
1024929                     NaN
1024930                     NaN
Name: project_name_en, Length: 1024931, dtype: str

In [43]:
capstone_ejari_2["area_id"]

0          465
1          319
2          334
3          372
4          463
          ...
1024926    334
1024927    395
1024928    305
1024929    360
1024930    266
Name: area_id, Length: 1024931, dtype: int64

In [51]:
capstone_ejari_2[["area_id", "area_name_en", "annual_amount"]]

         area_id                   area_name_en  annual_amount
0            465                 Wadi Al Safa 3      138000.00
1            319  Ras Al Khor Industrial Second       66667.00
2            334                       Al Jadaf       80000.00
3            372      Al Goze Industrial Second       39000.00
4            463                 Wadi Al Safa 7      724400.00
...          ...                            ...            ...
1024926      334                       Al Jadaf       43000.00
1024927      395     Jabal Ali Industrial First     2441880.00
1024928      305                      AL QUSAIS       28599.00
1024929      360              Muhaisanah Second     2925257.14
1024930      266                       Al Satwa       90000.00

[1024931 rows x 3 columns]

In [53]:
capstone[["area_id", "area_name_en", "actual_worth"]]

        area_id            area_name_en  actual_worth
0           441  Al Barsha South Fourth     1600000.0
1           465          Wadi Al Safa 3      460000.0
2           526            Business Bay      960000.0
3           343         Al Warsan First      317000.0
4           330             Marsa Dubai     1750000.0
...         ...                     ...           ...
872026      485          Me'Aisem First     1302965.0
872027      411          Palm Jabal Ali    69000000.0
872028      451         Al Hebiah Fifth     2170000.0
872029      249              Al Muteena     1350000.0
872030      351        Al Thanyah Third     1000000.0

[872031 rows x 3 columns]

In [55]:
capstone_ejari_2[["area_id", "area_name_en", "annual_amount", "contract_amount"]]

,area_id,area_name_en,annual_amount,contract_amount
0,465,Wadi Al Safa 3,138000.00,138000.0
1,319,Ras Al Khor Industrial Second,66667.00,66667.0
2,334,Al Jadaf,80000.00,80000.0
3,372,Al Goze Industrial Second,39000.00,39000.0
4,463,Wadi Al Safa 7,724400.00,724400.0
...,...,...,...,...
1024926,334,Al Jadaf,43000.00,43000.0
1024927,395,Jabal Ali Industrial First,2441880.00,2441880.0
1024928,305,AL QUSAIS,28599.00,28599.0
1024929,360,Muhaisanah Second,2925257.14,3412800.0
1024930,266,Al Satwa,90000.00,90000.0

In [56]:
capstone_ejari_2[["area_id", "area_name_en", "annual_amount", "contract_amount", "ejari_bus_property_type_en", "ejari_property_sub_type_en", "ejari_property_type_en" ]]

,area_id,area_name_en,annual_amount,contract_amount,ejari_bus_property_type_en,ejari_property_sub_type_en,ejari_property_type_en
0,465,Wadi Al Safa 3,138000.00,138000.0,Unit,Shop,Shop
1,319,Ras Al Khor Industrial Second,66667.00,66667.0,Virtual Unit,Warehouse,Warehouse
2,334,Al Jadaf,80000.00,80000.0,Unit,1bed room+Hall,Flat
3,372,Al Goze Industrial Second,39000.00,39000.0,Unit,1bed room+Hall,Flat
4,463,Wadi Al Safa 7,724400.00,724400.0,Unit,Clinic,Clinic
...,...,...,...,...,...,...,...
1024926,334,Al Jadaf,43000.00,43000.0,Unit,1bed room+Hall,Flat
1024927,395,Jabal Ali Industrial First,2441880.00,2441880.0,Unit,Room in labor Camp,Labor Camps
1024928,305,AL QUSAIS,28599.00,28599.0,Unit,1bed room+Hall,Flat
1024929,360,Muhaisanah Second,2925257.14,3412800.0,Virtual Unit,Labor Camp,Labor Camps
1024930,266,Al Satwa,90000.00,90000.0,Unit,2 bed rooms+hall,Flat

In [57]:
capstone_ejari_2[["area_id", "area_name_en", "annual_amount", "contract_amount", "ejari_bus_property_type_en", 
                  "ejari_property_sub_type_en", "ejari_property_type_en", "contract_end_date" ]]

,area_id,area_name_en,annual_amount,contract_amount,ejari_bus_property_type_en,ejari_property_sub_type_en,ejari_property_type_en,contract_end_date
0,465,Wadi Al Safa 3,138000.00,138000.0,Unit,Shop,Shop,2019-08-19
1,319,Ras Al Khor Industrial Second,66667.00,66667.0,Virtual Unit,Warehouse,Warehouse,2023-11-24
2,334,Al Jadaf,80000.00,80000.0,Unit,1bed room+Hall,Flat,2026-04-09
3,372,Al Goze Industrial Second,39000.00,39000.0,Unit,1bed room+Hall,Flat,2025-07-21
4,463,Wadi Al Safa 7,724400.00,724400.0,Unit,Clinic,Clinic,2019-01-31
...,...,...,...,...,...,...,...,...
1024926,334,Al Jadaf,43000.00,43000.0,Unit,1bed room+Hall,Flat,2022-10-09
1024927,395,Jabal Ali Industrial First,2441880.00,2441880.0,Unit,Room in labor Camp,Labor Camps,2019-01-31
1024928,305,AL QUSAIS,28599.00,28599.0,Unit,1bed room+Hall,Flat,2026-01-30
1024929,360,Muhaisanah Second,2925257.14,3412800.0,Virtual Unit,Labor Camp,Labor Camps,2023-07-31
1024930,266,Al Satwa,90000.00,90000.0,Unit,2 bed rooms+hall,Flat,2018-11-30

In [60]:
capstone[["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "instance_date" ]]

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,instance_date
0,441,Al Barsha South Fourth,1600000.0,Villa,Villa,Residential,2018-04-11
1,465,Wadi Al Safa 3,460000.0,Unit,Hotel Apartment,Hospitality,2024-08-08
2,526,Business Bay,960000.0,Unit,Flat,Residential,2024-06-04
3,343,Al Warsan First,317000.0,Unit,Flat,Residential,2013-08-12
4,330,Marsa Dubai,1750000.0,Unit,Flat,Residential,2022-11-22
...,...,...,...,...,...,...,...
872026,485,Me'Aisem First,1302965.0,Unit,Flat,Residential,2024-11-12
872027,411,Palm Jabal Ali,69000000.0,Land,NaN,Commercial,2025-10-07
872028,451,Al Hebiah Fifth,2170000.0,Land,NaN,Residential,2023-08-21
872029,249,Al Muteena,1350000.0,Building,NaN,Commercial,2013-04-23
872030,351,Al Thanyah Third,1000000.0,Unit,Flat,Residential,2016-07-21

In [63]:
capstone[["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "rooms_en", "instance_date" ]].head(100)

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,rooms_en,instance_date
0,441,Al Barsha South Fourth,1600000.0,Villa,Villa,Residential,3 B/R,2018-04-11
1,465,Wadi Al Safa 3,460000.0,Unit,Hotel Apartment,Hospitality,Studio,2024-08-08
2,526,Business Bay,960000.0,Unit,Flat,Residential,Studio,2024-06-04
3,343,Al Warsan First,317000.0,Unit,Flat,Residential,Studio,2013-08-12
4,330,Marsa Dubai,1750000.0,Unit,Flat,Residential,1 B/R,2022-11-22
...,...,...,...,...,...,...,...,...
95,412,Al Merkadh,1302600.0,Unit,Flat,Residential,1 B/R,2026-05-05
96,266,Al Satwa,16475000.0,Land,NaN,Commercial,NaN,2022-10-17
97,462,Madinat Al Mataar,589000.0,Unit,Flat,Residential,Studio,2026-06-25
98,484,Nadd Hessa,700000.0,Unit,Flat,Residential,1 B/R,2016-05-24
99,441,Al Barsha South Fourth,492277.0,Unit,Flat,Residential,1 B/R,2023-09-18

In [64]:
capstone[capstone["rooms_en"]== "3 B/R"]

,actual_worth,area_id,area_name_ar,area_name_en,building_name_ar,building_name_en,has_parking,instance_date,master_project_ar,master_project_en,...,reg_type_en,reg_type_id,rent_value,rooms_ar,rooms_en,transaction_id,trans_group_ar,trans_group_en,trans_group_id,load_timestamp
0,1600000.0,441,البرشاء جنوب الرابعة,Al Barsha South Fourth,NaN,NaN,0,2018-04-11,قرية جميرا الدائرية,Jumeirah Village Circle,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,1-11-2018-3852,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
25,2923000.0,531,الحبيه السادسة,Al Hebiah Sixth,NaN,NaN,0,2023-09-11,مدن,Mudon,...,Off-Plan Properties,0,NaN,ثلاث غرف,3 B/R,1-102-2023-43881,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
34,4060000.0,330,مرسى دبي,Marsa Dubai,اوشن هايتس,OCEAN HEIGHTS,1,2009-07-09,دبي مارينا,Dubai Marina,...,Off-Plan Properties,0,NaN,ثلاث غرف,3 B/R,1-102-2007-7501,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
40,1838888.0,467,وادي الصفا 5,Wadi Al Safa 5,NaN,NaN,0,2021-10-04,المرابع العربية 3,Arabian Ranches 3,...,Off-Plan Properties,0,NaN,ثلاث غرف,3 B/R,1-102-2021-17712,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
43,1980000.0,434,وادي الصفا 6,Wadi Al Safa 6,NaN,NaN,0,2010-03-31,المرابع العربية - 1,Arabian Ranches - 1,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,2-13-2010-1426,رهون,Mortgages,2,2026-07-08T18:22:29.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871924,6160874.0,390,برج خليفة,Burj Khalifa,العنوان رزيدنسز دبي اوبرا T1,The Address Residences Dubai Opera T1,1,2022-03-24,داون تاون دبي,DownTown Dubai,...,Off-Plan Properties,0,NaN,ثلاث غرف,3 B/R,1-102-2022-7937,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
871934,5323000.0,366,الكفاف,Al Kifaf,ريزيدنسز1 - 2,1 Residences - 2,1,2025-04-10,وصل 1,Wasl 1,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,1-41-2025-10743,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
871994,2497706.0,485,معيصم الأول,Me'Aisem First,NaN,NaN,0,2020-11-23,جميرا غولف للعقارات,Jumeirah Golf Estates,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,1-41-2020-6566,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
871995,1080000.0,507,اليلايس 2,Al Yelayiss 2,NaN,NaN,0,2020-12-17,تاون سكوير,TOWN SQUARE,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,2-13-2020-10278,رهون,Mortgages,2,2026-07-08T18:22:29.000Z
872008,3884000.0,333,مدينة دبي الملاحية,Madinat Dubai Almelaheyah,كورال ريف,CORAL REEF,1,2023-12-11,مدينة دبي الملاحية,Dubai Maritime City,...,Off-Plan Properties,0,NaN,ثلاث غرف,3 B/R,1-102-2023-65192,مبايعات,Sales,1,2026-07-08T18:22:29.000Z

In [72]:
capstone["nearest_metro_en"].isna().sum()

np.int64(272023)

In [73]:
capstone[["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "rooms_en", "nearest_metro_en", "instance_date" ]].head(100)

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,rooms_en,nearest_metro_en,instance_date
0,441,Al Barsha South Fourth,1600000.0,Villa,Villa,Residential,3 B/R,Dubai Internet City,2018-04-11
1,465,Wadi Al Safa 3,460000.0,Unit,Hotel Apartment,Hospitality,Studio,NaN,2024-08-08
2,526,Business Bay,960000.0,Unit,Flat,Residential,Studio,Buj Khalifa Dubai Mall Metro Station,2024-06-04
3,343,Al Warsan First,317000.0,Unit,Flat,Residential,Studio,Rashidiya Metro Station,2013-08-12
4,330,Marsa Dubai,1750000.0,Unit,Flat,Residential,1 B/R,Jumeirah Lakes Towers,2022-11-22
...,...,...,...,...,...,...,...,...,...
95,412,Al Merkadh,1302600.0,Unit,Flat,Residential,1 B/R,Buj Khalifa Dubai Mall Metro Station,2026-05-05
96,266,Al Satwa,16475000.0,Land,NaN,Commercial,NaN,Trade Centre Metro Station,2022-10-17
97,462,Madinat Al Mataar,589000.0,Unit,Flat,Residential,Studio,NaN,2026-06-25
98,484,Nadd Hessa,700000.0,Unit,Flat,Residential,1 B/R,NaN,2016-05-24
99,441,Al Barsha South Fourth,492277.0,Unit,Flat,Residential,1 B/R,Dubai Internet City,2023-09-18

In [74]:
capstone.head(5)

,actual_worth,area_id,area_name_ar,area_name_en,building_name_ar,building_name_en,has_parking,instance_date,master_project_ar,master_project_en,...,reg_type_en,reg_type_id,rent_value,rooms_ar,rooms_en,transaction_id,trans_group_ar,trans_group_en,trans_group_id,load_timestamp
0,1600000.0,441,البرشاء جنوب الرابعة,Al Barsha South Fourth,NaN,NaN,0,2018-04-11,قرية جميرا الدائرية,Jumeirah Village Circle,...,Existing Properties,1,NaN,ثلاث غرف,3 B/R,1-11-2018-3852,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
1,460000.0,465,وادي الصفا 3,Wadi Al Safa 3,سمايا,SAMAYA,1,2024-08-08,ماجان,Majan,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2024-29367,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
2,960000.0,526,الخليج التجارى,Business Bay,واترز ايدج,WATER'S EDGE,1,2024-06-04,الخليج التجاري,Business Bay,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2024-20211,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
3,317000.0,343,ورسان الاولى,Al Warsan First,واي - 20,Y-20,0,2013-08-12,المدينة العالمية - المرحلة الاولى,International City Phase 1,...,Existing Properties,1,NaN,استوديو,Studio,1-11-2013-24109,مبايعات,Sales,1,2026-07-08T18:22:29.000Z
4,1750000.0,330,مرسى دبي,Marsa Dubai,فيدا ريزيدنسز دبي مارينا,VIDA Residences Dubai Marina,1,2022-11-22,دبي مارينا,Dubai Marina,...,Off-Plan Properties,0,NaN,غرفة,1 B/R,1-102-2022-38762,مبايعات,Sales,1,2026-07-08T18:22:29.000Z

In [75]:
capstone_ejari_2.head(5)

,actual_area,annual_amount,area_id,area_name_ar,area_name_en,contract_amount,contract_end_date,contract_id,contract_reg_type_ar,contract_reg_type_en,...,no_of_prop,project_name_ar,project_name_en,project_number,property_usage_ar,property_usage_en,tenant_type_ar,tenant_type_en,tenant_type_id,load_timestamp
0,79.99,138000.0,465,وادي الصفا 3,Wadi Al Safa 3,138000.0,2019-08-19,CNT848254060,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
1,NaN,66667.0,319,راس الخور الصناعيه الثانيه,Ras Al Khor Industrial Second,66667.0,2023-11-24,CNT2052130227,تجديد,Renew,...,1,NaN,NaN,NaN,تجاري,Commercial,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
2,65.70,80000.0,334,الجداف,Al Jadaf,80000.0,2026-04-09,CRT2130401186,جديد,New,...,1,D1,D1,623.0,سكني,Residential,شخص,Person,0.0,2026-07-08T18:25:35.000Z
3,55.72,39000.0,372,القوز الصناعيه الثانيه,Al Goze Industrial Second,39000.0,2025-07-21,CNT2117553166,تجديد,Renew,...,1,NaN,NaN,NaN,سكني,Residential,جهة,Authority,1.0,2026-07-08T18:25:35.000Z
4,673.00,724400.0,463,وادي الصفا 7,Wadi Al Safa 7,724400.0,2019-01-31,CNT743999615,جديد,New,...,1,المدينة المستدامة,THE SUSTAINABLE CITY,1390.0,منشأه صحيه,Health Facility,جهة,Authority,1.0,2026-07-08T18:25:35.000Z

In [77]:
condition = capstone['rooms_en'] == '4 B/R'
result = capstone.loc[condition, ["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "rooms_en", "nearest_metro_en", "instance_date"]]

In [78]:
result

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,rooms_en,nearest_metro_en,instance_date
46,506,Al Yelayiss 1,2712000.0,Villa,Villa,Residential,4 B/R,NaN,2026-03-16
177,507,Al Yelayiss 2,2800000.0,Villa,Villa,Residential,4 B/R,NaN,2025-12-09
182,463,Wadi Al Safa 7,2104000.0,Villa,Villa,Residential,4 B/R,NaN,2021-06-21
204,507,Al Yelayiss 2,2640000.0,Villa,Villa,Residential,4 B/R,NaN,2025-05-21
214,485,Me'Aisem First,1864524.0,Unit,Flat,Residential,4 B/R,Damac Properties,2019-05-23
...,...,...,...,...,...,...,...,...,...
871923,458,Dubai Investment Park First,1600000.0,Villa,Villa,Residential,4 B/R,DANUBE Metro Station,2022-02-02
871965,506,Al Yelayiss 1,2903000.0,Villa,Villa,Residential,4 B/R,NaN,2026-02-17
871974,465,Wadi Al Safa 3,3703201.0,Villa,Villa,Residential,4 B/R,NaN,2023-04-11
871991,482,Hadaeq Sheikh Mohammed Bin Rashid,5200000.0,Villa,Villa,Residential,4 B/R,First Abu Dhabi Bank Metro Station,2025-05-09
872024,506,Al Yelayiss 1,2746000.0,Villa,Villa,Residential,4 B/R,NaN,2026-02-13

In [81]:
condition_1 = capstone['rooms_en'] == '4 B/R'
condition_2 = capstone['property_sub_type_en'] == 'Flat'
result_2 = capstone.loc[(condition_1) & (condition_2), ["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "rooms_en", "nearest_metro_en", "instance_date"]]

In [82]:
result_2

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,rooms_en,nearest_metro_en,instance_date
214,485,Me'Aisem First,1864524.0,Unit,Flat,Residential,4 B/R,Damac Properties,2019-05-23
230,410,Palm Jumeirah,8439247.0,Unit,Flat,Residential,4 B/R,Palm Jumeirah,2023-03-21
282,330,Marsa Dubai,22668379.0,Unit,Flat,Residential,4 B/R,Jumeirah Beach Resdency,2025-01-20
597,350,Al Thanyah Fifth,2865000.0,Unit,Flat,Residential,4 B/R,Marina Mall Metro Station,2014-07-21
755,410,Palm Jumeirah,3600000.0,Unit,Flat,Residential,4 B/R,Palm Jumeirah,2018-12-11
...,...,...,...,...,...,...,...,...,...
870833,526,Business Bay,3200000.0,Unit,Flat,Residential,4 B/R,Business Bay Metro Station,2013-01-10
870898,330,Marsa Dubai,4200000.0,Unit,Flat,Residential,4 B/R,Jumeirah Beach Resdency,2008-06-12
871175,330,Marsa Dubai,9500000.0,Unit,Flat,Residential,4 B/R,Mina Seyahi,2018-06-21
871284,432,Palm Deira,10955000.0,Unit,Flat,Residential,4 B/R,Palm Deira Metro Stations,2025-09-15
871719,330,Marsa Dubai,3000000.0,Unit,Flat,Residential,4 B/R,Jumeirah Lakes Towers,2015-08-25

In [85]:
condition_3 = capstone['rooms_en'] == '4 B/R'
condition_4 = capstone['property_sub_type_en'] == 'Villa'
result_3 = capstone.loc[(condition_3) & (condition_4), ["area_id", "area_name_en", "actual_worth", "property_type_en", 
                  "property_sub_type_en", "property_usage_en", "rooms_en", "nearest_metro_en", "instance_date"]]

In [86]:
result_3

,area_id,area_name_en,actual_worth,property_type_en,property_sub_type_en,property_usage_en,rooms_en,nearest_metro_en,instance_date
46,506,Al Yelayiss 1,2712000.0,Villa,Villa,Residential,4 B/R,NaN,2026-03-16
177,507,Al Yelayiss 2,2800000.0,Villa,Villa,Residential,4 B/R,NaN,2025-12-09
182,463,Wadi Al Safa 7,2104000.0,Villa,Villa,Residential,4 B/R,NaN,2021-06-21
204,507,Al Yelayiss 2,2640000.0,Villa,Villa,Residential,4 B/R,NaN,2025-05-21
281,441,Al Barsha South Fourth,620199.0,Villa,Villa,Residential,4 B/R,Dubai Internet City,2016-06-06
...,...,...,...,...,...,...,...,...,...
871923,458,Dubai Investment Park First,1600000.0,Villa,Villa,Residential,4 B/R,DANUBE Metro Station,2022-02-02
871965,506,Al Yelayiss 1,2903000.0,Villa,Villa,Residential,4 B/R,NaN,2026-02-17
871974,465,Wadi Al Safa 3,3703201.0,Villa,Villa,Residential,4 B/R,NaN,2023-04-11
871991,482,Hadaeq Sheikh Mohammed Bin Rashid,5200000.0,Villa,Villa,Residential,4 B/R,First Abu Dhabi Bank Metro Station,2025-05-09
872024,506,Al Yelayiss 1,2746000.0,Villa,Villa,Residential,4 B/R,NaN,2026-02-13